source: "."
encoding: UTF-8

title: "12 паттернов, которыми мы руководствуемся в работе - DevOps Factors"
description: >
  12 паттернов, которыми мы руководствуемся в работе DevOps - о приоритетах, о коммуникации, о автоматизации,
  о структуре команды, о шаринге опыта, о механизмах мониторинга, о Continious Integration и другое

collections:
  factors:
    output: true

sass:
  sass_dir: _sass
  style: compressed